jobs:
  job_upload:
    name: Upload Release Assets
    needs: [build_x64_native, build_arm]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./

      - name: File checksums
        run: |
          rm src/stub.go
          sha256sum * > sha256sums.txt
          cat sha256sums.txt
          file *

      - name: Upload artifacts # Upload checksums to artifact. Useful if not a tagged release.
        uses: actions/upload-artifact@v2
        with:
          name: stubs
          path: "stubs/sha256sums.txt"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            stubs/linux
            stubs/linux-arm64
            stubs/linux-armv6
            stubs/linux-armv7
            stubs/macos
            stubs/windows.exe
            stubs/sha256sums.txt
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
